apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "admission-webhook.fullname" . }}-mutating
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
webhooks:
  - name: mutator.{{ .Release.Namespace }}.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    clientConfig:
      service:
        name: {{ include "admission-webhook.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: {{ .Values.service.port }}
      caBundle: {{ .Values.webhook.caBundle }}
    rules:
      {{- range .Values.webhook.rules }}
      - operations: {{ .operations | toJson }}
        apiGroups: {{ .apiGroups | toJson }}
        apiVersions: {{ .apiVersions | toJson }}
        resources: {{ .resources | toJson }}
        scope: {{ .scope | default "*" }}
      {{- end }}
    namespaceSelector:
      {{- with .Values.webhook.namespaceSelector }}
      matchLabels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    objectSelector:
      {{- with .Values.webhook.objectSelector }}
      matchLabels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    reinvocationPolicy: Never
