apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admission-webhook.fullname" . }}-tls
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
