apiVersion: v1
kind: Service
metadata:
  name: {{ include "admission-webhook.fullname" . }}
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "admission-webhook.selectorLabels" . | nindent 4 }}
