apiVersion: v2
name: admission-webhook
description: A Helm chart for Kubernetes Admission Webhook Server
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: DevOps Team
dependencies:
  - name: cert-manager
    version: "1.12.0"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
